#!/usr/bin/env node

var fs   = require("fs");
var path = require("path");
var exec = require("child_process").exec;

require.paths.unshift(
  path.dirname(
    fs.realpathSync(__filename)
  )
);

exec("which coffee && which cafe", function(error, stdOutput, stdError) {
  if (stdError) {
    console.log(stdError);
  }

  if (error) {
    throw error;
  }

  if (! stdOutput) {
    return;
  }

  var pare = stdOutput.trim().replace(/\n/g, " ").split(/\s+/);

  var coffeePath = fs.realpathSync(pare[0]);
  var cafePath   = fs.realpathSync(pare[1]);

  var coffeeLibPath = path.normalize(path.dirname(coffeePath) + "/../lib/node/coffee-script");
  var cafeLibPath   = path.normalize(path.dirname(cafePath)   + "/../lib");

  var coffee       = require(coffeeLibPath);
  var OptionParser = require(coffeeLibPath + "/optparse").OptionParser;
  var Compiler     = require("compiler").Compiler

  var compiler = new Compiler(
    coffee,
    cafeLibPath,
    new OptionParser(Compiler.options,"").parse(process.argv.slice(2))
  );

  compiler.setPrinter(require("util"));

  compiler.run();
});
